### ISSUE TITLE
[Bug] Commands Multiworld in console not use !

### ISSUE THREAD

**Issue by Lennord** [Dev7ex/MultiWorld#1]
Hello, your plugin is good there is no problem except when you use the multiworld commands in the console nothing happens, I think it would be good if you correct it, thank you and good luck...

Version Minecraft: 1.16.5
Paper version: 1.16.5
MultiWorld version: 1.0.0-SNAPSHOT
No error console...

**Comment by Dev7ex** [comment]
Hey! that the commands dont work in the console was actually intended. But that you dont get feedback like a message was my mistake. 
I add this feature in the next version

**Comment by Lennord** [comment]
> Hey! that the commands dont work in the console was actually intended. But that you dont get feedback like a message was my mistake.
> I add this feature in the next version

Ok thank you, on the other hand can you put all the messages from the config like command syntax and others...

**Comment by Dev7ex** [comment]
Done!
