### ISSUE TITLE
Command "/world back" not applying per-world gamemode (1.4.1-SNAPSHOT)

### ISSUE THREAD

**Issue by Ting3l** [Dev7ex/MultiWorld#12]
When using the command "/world back" the gamemode set in world.yml is not apllied to the player. 
Instead the current gamemode is kept.
When using the command "/world teleport <world>" everything works fine.

Versions:
MultiWorld-Bukkit-1.4.1-SNAPSHOT.jar
FacilisCommon-Bukkit-1.0.1-SNAPSHOT.jar
Purpur Server 1.20.1

I have one world set to gamemode SURVIVAL and one set to SPECTATOR.
By using the two commands mentioned above in any combination I can get the wrong gamemode per world.
This is repeatable and consistent.

**Comment by Dev7ex** [comment]
Fixed (https://github.com/Dev7ex/MultiWorld/commit/dc9082cc33bd7a60abbfa2179fb69b17b7fa1a4b)
Version 1.4.2-SNAPSHOT
