### ISSUE TITLE
Request for a Feature to Disable Portal Functionality in a Specific World

### ISSUE THREAD

**Issue by DimaSergeew** [Dev7ex/MultiWorld#14]
Dear Development,

I am reaching out to propose the addition of a new feature that could greatly improve the experience for many users in multi-world server environments. This proposed feature involves providing server administrators the ability to disable the functionality of portals to other dimensions (such as the Nether and the End) within a specific world.

The motivation for this request stems from a desire to control and guide player progression within certain worlds, such as a Hub world, where unrestricted access to other dimensions may not be desirable. It would be beneficial to have a feature that allows us to manage whether portals in a given world can send players to other dimensions. This feature could bring about an improved degree of flexibility in managing player experience and progression.

Thank you for considering my proposal. I believe that this addition would be a meaningful improvement to the current system, benefiting a wide range of server administrators and players alike.

**Comment by Dev7ex** [comment]
Added (https://github.com/Dev7ex/MultiWorld/commit/e9c9bca32f2b8c2483af1e34462e8e75833cff22)
Version 1.4.3-SNAPSHOT
