### ISSUE TITLE
Could not pass event PluginEnableEvent to FacilisCommon

### ISSUE THREAD

**Issue by kartibrown** [Dev7ex/MultiWorld#16]
Hello, I'm running a paper server version 84 and I just updated from 1.4.2 to 1.4.3 and got this [Error.txt](https://github.com/Dev7ex/MultiWorld/files/12135856/Error.txt)

I throw in the PluginsList aswell

> ChestSort
EconomyShopGUI
EssentialsX + chat + spawn
EvenMoreFish
FacilisCommon
GriefPrevention
GrimAC
IllegalStack
LuckPerms
MultiWorld
PlayerParticles
PunishGUI
Spark
TreeAssist
Vault
ViewDistanceTweaks
WildRTP
WorldEdit
WorldGuard

And also the whole log because why not:
[2023-07-22-4.log](https://github.com/Dev7ex/MultiWorld/files/12135868/2023-07-22-4.log)

EDIT:
I tested putting only FacilisCommon and MultiWorld 1.4.3 in the plugins folder but I still get the same error.

**Comment by Dev7ex** [comment]
You have to delete the config.yml or add 

settings:
  # Standard values for new worlds
  defaults:
    end-portal-accessible: true
    nether-portal-accessible: true
