### ISSUE TITLE
Per World Inventories and Enderchests

### ISSUE THREAD

**Issue by DontActLikeMe** [Dev7ex/MultiWorld#20]
im currently trying to add a "creative world" where my players can test their builds and palates and then go back to survival world and build based on their designs. I am Requesting a per world inventory feature.would also need enderchest support. just thinking how players could try and trick the system. Please change this to an enhancement. I know multiverse had multiverse inventories that helped with this.

**Comment by Dev7ex** [comment]
This function is not planned for the time being. 
MultiWorld should be a simple plugin which is only responsible for the pure world management.

Something like this would be an idea for an addon
