### ISSUE TITLE
Nether portals all get linked

### ISSUE THREAD

**Issue by MinerCoffee** [Dev7ex/MultiWorld#22]
All the portals are being linked to one. Ex: going in the nether from overworld and then leaving it goes the one portal even though they should not be linked.

**Comment by Dev7ex** [comment]
Please show me your config and the world.yml

**Comment by MinerCoffee** [comment]
#
#      __  ___      ____  _ _       __           __    __
#    /  |/  /_  __/ / /_(_) |     / /___  _____/ /___/ /
#   / /|_/ / / / / / __/ /| | /| / / __ \/ ___/ / __  /
#  / /  / / /_/ / / /_/ / | |/ |/ / /_/ / /  / / /_/ /
# /_/  /_/\__,_/_/\__/_/  |__/|__/\____/_/  /_/\__,_/
#
# Copyright (c) 2023 by Dev7ex
# Version: 1.4.6-SNAPSHOT
config-version: 1.4.6-SNAPSHOT
# General
prefix: Â§8[Â§bMultiWorldÂ§8]Â§r
no-permission: Â§cIm sorry, but you do not have permission to perform this command.
  Please contact the server administrators if you believe that is in error.
player-not-found: '%prefix% Â§cThis player could not be found'
only-player-command: '%prefix% Â§cThis command can only performed by a player'

settings:
  # Worlds that should be loaded when the server starts
  # WARNING: When the world is not registered by MultiWorld the world will not be loaded
  # The world has to be imported manually! (Attention choose the correct WorldType)
  # Example: auto-load: [world1, world2, world3]
  auto-load: []
  # Should all players with the permission (multiworld.notify.update)
  # get a message when entering server
  receive-update-message: true
  # Should the auto-gamemode per world work?
  auto-game-mode-enabled: true
  # Should you be able to enter Nether/End worlds with the command /world telport <Player> <World>
  access-nether-world-via-command: true
  access-end-world-via-command: true
  # Should MultiWorld connect the worlds with each other via the registered data?
  world-link-enabled: true
  # Standard values for new worlds
  defaults:
    normal-world: world
    end-world: world_the_end
    nether_world: world_nether
    difficulty: HARD
    game-mode: SURVIVAL
    pvp-enabled: true
    spawn-animals: true
    spawn-monsters: true
    end-portal-accessible: true
    nether-portal-accessible: true
    whitelist-enabled: false

messages:
  general:
    update-message-player: '%prefix% Â§7There is a new update available. Â§8[Â§bhttps://www.spigotmc.org/resources/multiworld.92559Â§8]'
    update-message-version-player: '%prefix% Â§7Current Version: Â§b%current_version%
      Â§7New Version Â§b%new_version%'
    world-not-exists: '%prefix% Â§cThe specified world does not exist!'
    world-not-loaded: '%prefix% Â§cThe specified world is not loaded!'
    world-already-exists: '%prefix% Â§cThe specified world already exists!'
    world-type-not-exists: '%prefix% Â§cThe specified WorldType does not exist'
    world-folder-not-exists: '%prefix% Â§cNo world folder could be found!'
    world-whitelist-block-trespassing: '%prefix% Â§7You are not on the whitelist of
      this world!'
  commands:
    back:
      usage: '%prefix% Â§cUsage: /world back'
      world-not-exists: '%prefix% Â§cThere is no world you can go!'
      sender-already-there: '%prefix% Â§cYou are already in the world Â§b%world_name%'
    backup:
      usage: '%prefix% Â§cUsage: /world backup <World>'
      starting: '%prefix% Â§7A backup of the world Â§b%world_name% is created...'
      finished: '%prefix% Â§7The backup of the world Â§b%world_name% Â§7has been successfully
        created!'
    clone:
      usage: '%prefix% Â§cUsage: /world clone <World> <Name>'
      starting: '%prefix% Â§7The world Â§b%world_name% Â§7will be copied...'
      finished: '%prefix% Â§7The world Â§b%world_name% Â§7has been successfully copied!'
    create:
      usage: '%prefix% Â§cUsage: /world create <Name> <Generator | Seed | WorldType>'
      starting: '%prefix% Â§7The world Â§b%world_name% Â§7will be created...'
      finished: '%prefix% Â§7The world Â§b%world_name% Â§7was created successfully!'
    delete:
      usage: '%prefix% Â§cUsage: /world delete <World>'
      world-cannot-deleted: '%prefix% Â§cThe specified world may not be deleted!'
      starting: '%prefix% Â§7The world Â§b%world_name% Â§7will be deleted...'
      finished: '%prefix% Â§7The world Â§b%world_name% Â§7has been successfully deleted!'
    flag:
      usage: '%prefix% Â§cUsage: /world flag <World> <Flag> <Value>'
      not-existing: '%prefix% Â§cThis flag does not exist'
      value-not-existing: '%prefix% Â§cThis value does not exist for the flag Â§b%flag%'
      successfully-set: '%prefix% Â§7The flag Â§b%flag% Â§7was set to Â§b%value% Â§7!'
    help:
      message:
      - ''
      - 'Â§fÂ§m                    Â§rÂ§r %prefix% Â§fÂ§m                    '
      - ''
      - Â§7Â» Â§7/world Â§bback
      - Â§7Â» Â§7/world Â§bbackup Â§7<World>
      - Â§7Â» Â§7/world Â§bclone Â§7<World> <Name>
      - Â§7Â» Â§7/world Â§bcreate Â§7<Name> <WorldType | Seed | Generator>
      - Â§7Â» Â§7/world Â§bdelete Â§7<World>
      - Â§7Â» Â§7/world Â§bflag Â§7<World> <Property> <Value>
      - Â§7Â» Â§7/world Â§bhelp
      - Â§7Â» Â§7/world Â§bimport Â§7<World> <WorldType>
      - Â§7Â» Â§7/world Â§binfo Â§7<World>
      - Â§7Â» Â§7/world Â§blist
      - Â§7Â» Â§7/world Â§blink Â§7<World> <Nether | End> <Welt>
      - Â§7Â» Â§7/world Â§bload Â§7<World>
      - Â§7Â» Â§7/world Â§breload
      - Â§7Â» Â§7/world Â§bteleport Â§7<Player> <Welt>
      - Â§7Â» Â§7/world Â§bunload Â§7<World>
      - Â§7Â» Â§7/world Â§bwhitelist Â§7<World> <Enable | Disable | Add | Remove | List>
        <Name>
      - ''
      - 'Â§fÂ§m                    Â§rÂ§r %prefix% Â§fÂ§m                    '
      - ''
    import:
      usage: '%prefix% Â§cUsage: /world import <Name> <WorldType | Generator>'
      world-already-imported: '%prefix% Â§7The world Â§b%world_name% Â§7is already imported!'
      starting: '%prefix% Â§7The world Â§b%world_name% Â§7will import...'
      finished: '%prefix% Â§7The world Â§b%world_name% Â§7was successfully imported!'
    info:
      usage: '%prefix% Â§cUsage: /world info <World>'
      message:
      - ''
      - 'Â§fÂ§m               Â§rÂ§r Â§b%world_name% Â§fÂ§m               '
      - ''
      - 'Â§7Â» Creator: Â§b%world_creator_name%'
      - 'Â§7Â» Created at: Â§b%creation_timestamp%'
      - 'Â§7Â» Loaded: Â§b%loaded%'
      - 'Â§7Â» WorldType: Â§b%world_type%'
      - 'Â§7Â» Environment: Â§b%environment%'
      - 'Â§7Â» Difficulty: Â§b%difficulty%'
      - 'Â§7Â» GameMode: Â§b%gamemode%'
      - 'Â§7Â» Pvp: Â§b%pvp_enabled%'
      - 'Â§7Â» Spawn-Monster: Â§b%spawn_monsters%'
      - 'Â§7Â» Spawn-Animals: Â§b%spawn_animals%'
      - 'Â§7Â» End-Portal-Accessible: Â§b%end-portal-accessible%'
      - 'Â§7Â» Nether-Portal-Accessible: Â§b%nether-portal-accessible%'
      - 'Â§7Â» Whitelist: Â§b%whitelist_enabled%'
      - ''
      - 'Â§fÂ§m               Â§rÂ§r Â§b%world_name% Â§fÂ§m               '
      - ''
    list:
      usage: '%prefix% Â§cUsage: /world list'
      message: '%prefix% Â§aWorlds: %world_names%'
    link:
      usage: '%prefix% Â§cUsage: /world link <World> <End | Nether> <World>'
      environment-not-exists: '%prefix% Â§cThe specified environment does not exist!'
      successfully-set: '%prefix% Â§7You have connected the portal of the environment
        Â§b%environment_name% Â§7in the world Â§b%world_name% Â§7with the world Â§b%target_world_name%'
    load:
      usage: '%prefix% Â§cUsage: /world load <Name>'
      world-already-loaded: '%prefix% Â§7The world Â§bworld_name% Â§7is already loaded!'
      starting: '%prefix% Â§7The world Â§b%world_name% Â§7will loaded...'
      finished: '%prefix% Â§7The world Â§b%world_name% Â§7was successfully loaded!'
    reload:
      usage: '%prefix% Â§cUsage: /world reload'
      message: '%prefix% Â§7The configurations has been reloaded!'
    teleport:
      usage: '%prefix% Â§cUsage: /world teleport <Player> <World>'
      message: '%prefix% Â§a%player_name% Â§7is teleported to the world Â§b%world_name%
        Â§7!'
      sender-already-there: '%prefix% Â§7You are already in the world Â§b%world_name%'
      target-already-there: '%prefix% Â§7The player Â§a%player_name% Â§7is already in
        the world Â§b%world_name%'
      nether-not-accessible: '%prefix% Â§cYou cant enter the Nether via the command!'
      end-not-accessible: '%prefix% Â§cYou cant enter the end via the command!'
    unload:
      usage: '%prefix% Â§cUsage: /world unload <World>'
      world-cannot-unloaded: '%prefix% Â§cThe specified world must not be unloaded!'
      starting: '%prefix% Â§7The world Â§b%world_name% Â§7will be unloaded...'
      finished: '%prefix% Â§7The world Â§b%world_name% Â§7was successfully unloaded!'
      chunk-starting: '%prefix% Â§7The chunks in Â§b%world_name% Â§7are unloaded...'
      chunk-finished: '%prefix% Â§7The chunks in Â§b%world_name% Â§7were successfully
        unloaded!'
      chunk-teleport: '%prefix% Â§7The world you were in will be unloaded. You will
        be teleported!'
    whitelist:
      usage: '%prefix% Â§cUsage: /world whitelist <World> <On | Off | Add | List |
        Remove> <Player>'
      add:
        already-added: '%prefix% Â§The player %player_name% Â§7is already Â§7on the whitelist!'
        successfully-added: '%prefix% Â§7You have added %player_name% Â§7to the whitelist
          of world Â§b%world_name%'
      list:
        empty: '%prefix% Â§7The whitelist for world Â§b%world_name% Â§7is empty'
        message: '%prefix% Â§7Whitelist: %player_names%'
      disable:
        already-disabled: '%prefix% Â§7World whitelist Â§b%world_name% Â§7is already
          disabled!'
        successfully-disabled: '%prefix% Â§7You have disabled the whitelist in the
          world Â§b%world_name%Â§7!'
      enable:
        already-enabled: '%prefix% Â§7The world whitelist Â§b%world_name% Â§7is already
          activated!'
        successfully-enabled: '%prefix% Â§7You have activated the whitelist in the
          world Â§b%world_name% Â§7!'
      remove:
        already-removed: '%prefix% Â§7The player %player_name% Â§7is Â§not Â§7on the whitelist!'
        successfully-removed: '%prefix% Â§7You have %player_name% Â§7removed from the
          Â§b%world_name% Â§7whitelist'
defaults:
  nether-portal-accessible: true

**Comment by MinerCoffee** [comment]
world:
  creator-name: CONSOLE
  creation-timestamp: 1696795987075
  type: NORMAL
  game-mode: SURVIVAL
  difficulty: PEACEFUL
  pvp-enabled: true
  spawn-animals: true
  spawn-monsters: true
  end-portal-accessible: true
  nether-portal-accessible: true
  end-world: world_the_end
  nether-world: world_nether
  normal-world: world
  whitelist: []
  whitelist-enabled: false
world_nether:
  creator-name: CONSOLE
  creation-timestamp: 1696795987077
  type: NETHER
  game-mode: SURVIVAL
  difficulty: PEACEFUL
  pvp-enabled: true
  spawn-animals: true
  spawn-monsters: true
  end-portal-accessible: true
  nether-portal-accessible: true
  end-world: world_the_end
  nether-world: world_nether
  normal-world: world
  whitelist: []
  whitelist-enabled: false
world_the_end:
  creator-name: CONSOLE
  creation-timestamp: 1696795987078
  type: END
  game-mode: SURVIVAL
  difficulty: PEACEFUL
  pvp-enabled: true
  spawn-animals: true
  spawn-monsters: true
  end-portal-accessible: true
  nether-portal-accessible: true
  end-world: world_the_end
  nether-world: world_nether
  normal-world: world
  whitelist: []
  whitelist-enabled: false
flatroom:
  creator-name: MinerCoffee97
  creation-timestamp: 1696796373827
  type: FLAT
  game-mode: SURVIVAL
  difficulty: HARD
  pvp-enabled: true
  spawn-animals: true
  spawn-monsters: true
  end-portal-accessible: true
  nether-portal-accessible: true
  end-world: world_the_end
  nether-world: world_nether
  normal-world: world
  whitelist: []
  whitelist-enabled: false
testing-area:
  creator-name: MinerCoffee97
  creation-timestamp: 1696796381187
  type: FLAT
  game-mode: SURVIVAL
  difficulty: HARD
  pvp-enabled: true
  spawn-animals: true
  spawn-monsters: true
  end-portal-accessible: true
  nether-portal-accessible: true
  end-world: world_the_end
  nether-world: world_nether
  normal-world: world
  whitelist: []
  whitelist-enabled: false

**Comment by Dev7ex** [comment]
Set world-link-enabled to false. This function will be removed soon and should be moved to a separate plugin

**Comment by MinerCoffee** [comment]
it works now thanks
