### ISSUE TITLE
Placeholder %player_name% + loading config command

### ISSUE THREAD

**Issue by Gindoma** [Dev7ex/MultiWorld#24]
Heye Dev7ex, I would find it cool if you could create a world with the player executing the command when using the command /world create [%playername%]. 

And if you add an autoload function with a command like /mw config load [%player_name%] to not manually add the world to the config for autoload.

**Comment by Gindoma** [comment]
Ps: command zum laden für config hinzufügen auto load

**Comment by Dev7ex** [comment]
Hey,

Your suggestion with the "placeholders" is planned for the next update.

The suggestion with the command /mw config will also follow afterwards, just a bit "bigger"

**Comment by Dev7ex** [comment]
Your suggestion with the placeholders was implemented in version 1.4.8.

Your other suggestion will follow in a future update.

**Comment by Dev7ex** [comment]
This function has been slightly modified and introduced in the latest version
