### ISSUE TITLE
Auto Load Improvement

### ISSUE THREAD

**Issue by Maschlax** [Dev7ex/MultiWorld#26]
It would be nice if you could add a command where you can add auto-loaded worlds.
You could also make it in the config like:
```
auto-load: []
invert: true
```
So that it would load all the worlds except those that are in there.

**Comment by Dev7ex** [comment]
Hey,

Your suggestion with the em Command /mw config is probably planned for MultiWorld 1.5.0!

**Comment by Dev7ex** [comment]
This function has been slightly modified and introduced in the latest version
