### ISSUE TITLE
Dependency missing?

### ISSUE THREAD

**Issue by itsTyrion** [Dev7ex/MultiWorld#3]
I want to make a PR with an Event fired after the initial world load but I cannot build the project because of the missing dep.
What's the maven repo for it?

**Comment by Dev7ex** [comment]
https://github.com/Dev7ex/maven-common

**Comment by itsTyrion** [comment]
So there is no repo and you need to install it to your local repo?

**Comment by Dev7ex** [comment]
Yeah my maven common has no public repository you need to install in local.
