### ISSUE TITLE
Entities and Mobs not dropping items

### ISSUE THREAD

**Issue by geewah** [Dev7ex/MultiWorld#30]
After using the mod for a few hours the server would no longer drop any items from inventory, mob drops, or block breaks. This was tested in all three vanilla dimensions and the gamerule doEntityDrops, as well as doItemDrops had no effect. Only creatures and blocks broken in the modded MultiWorlds would drop items from any source.

**Comment by Dev7ex** [comment]
Set the WorldFlag SPAWN_ENTITIES to true. I forgot to include something like that there, I'll fix it in a few days

**Comment by Dev7ex** [comment]
Has been fixed in version 1.5.4
