### ISSUE TITLE
Bug whitelist

### ISSUE THREAD

**Issue by ANB9** [Dev7ex/MultiWorld#33]
When you create a world using the command "/world create test", and then turn on the whitelist "/world whitelist test enable" and try to add a person to this world, then the command "/world whitelist test add test" returns an error in the command.
![image](https://github.com/Dev7ex/MultiWorld/assets/112416382/f16ccc09-2b6f-4bee-a82d-a2ceb830f9cf)
![image](https://github.com/Dev7ex/MultiWorld/assets/112416382/f09b5507-a891-4e52-be8a-2747da479689)

**Comment by Dev7ex** [comment]
Found the bug will be fixed in version 1.5.7 thanks for your message
