### ISSUE TITLE
World with special generators couldn't be load when server starting.

### ISSUE THREAD

**Issue by qyl27** [Dev7ex/MultiWorld#46]
Plugin version: 1.6.5

Current behavior:
The server shows `The world flat cannot be loaded because the generator FlatWorldGenerator is not installed` at the server starting.  
But, loading the world manually by `/multiworld load flat` will be successful.  

Expect behavior: 
The world should be auto-loaded at starting successfully.

Steps to reproduce: 
1. Create a world with generators, e.g. `/multiworld create flat NORMAL -g FlatWorldGenerator`
2. Flag it as auto load, `/multiworld flag flat AUTO_LOAD_ENABLED true`
3. Restart the server

**Comment by Dev7ex** [comment]
Found the error, which will be fixed during the course of the day. Thank you for reporting it

**Comment by Dev7ex** [comment]
Fixed
